[build]
  base = "safarset"
  command = "npm run build"
  publish = "safarset/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_ENABLED = "false"
